services:
  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - POSTGRES_DB=postgres
    ports:
      - 5438:5432
    expose:
      - 5438
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db:
